server:
  port: 8888

spring:
  application:
    name: blogDemo
  #    数据库
  datasource:
    url: jdbc:mysql://localhost:3306/blogDemo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#   mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
